config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base

  scope :three, -> { order(created_at: :desc).limit(3)}

  scope :volantis, -> { where(origin: "Volantis") }

  scope :most_reviews, -> {(
    select("products.id, products.name, products.origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}

  has_many :reviews

  validates :name, :price, :origin, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base

  scope :three, -> { order(created_at: :desc).limit(3)}

  scope :volantis, -> { where(origin: "Volantis") }

  scope :most_reviews, -> {(
    select("projects.id, projects.name, projects.origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("projects.id")
    .order("reviews_count DESC")
    .limit(1)
    )}

  has_many :reviews

  validates :name, :price, :origin, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product

  validates :author, :presence => true
  validates_numericality_of :rating, { greater_than_or_equal_to: 1, less_than_or_equal_to: 5, :presence => true }
  validates :content_body, { length: { in: 50..250 }, :presence => true }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @features = Product.three
    @location = Product.volantis
    @most_reviews = Product.most_reviews
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product sucessfully added."
      redirect_to  products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :price, :origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review sucessfully added."
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render('layouts/errors', :object => @product) %>

<%= form_for [@product] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1>Welcome to Mario's Discount Snausages Products!</h1>

<h3>The finest in snausage product technology</h3>

<h3>Lastest Additions:</h3>
<% @features.each do |feature| %>
  <h4><%= feature.name %></h4>
<% end %>
<br>

<h3>The Snausage with the most reviews:</h3>
<% @most_reviews.each do |products| %>
  <h4><%= products.name %></h4>
<% end %>
<br>

<h3>And these fine snausages were made right here in Volantis:</h3>
<% @location.each do |products| %>
  <h4><%= products.name %></h4>
<% end %>
<br>

All Snausages:
<ul>
  <% @products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %> -
      $<%= link_to product.price, product_path(product) %> -
      <%= link_to product.origin, product_path(product) %></li>
  <% end %>
</ul>



<%= link_to "New Product", new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <ul>
    <% @product.reviews.each do |review| %>
      <li>
        <p>Review: <%= review.content_body %></p>
        <p>Author: <%= review.author %></p>
        <p>Rating: <%= review.rating %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>


  <%= link_to "Edit Snausage", edit_product_path %><br>
<p><%= link_to "Delete Product", product_path(@product),
                        :data => {:confirm => "Are you sure?",
                        :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/projects/_form.html.erb
<%= render('layouts/errors', :object => @project) %>

<%= form_for [@project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<% if @project.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render "form" %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form" %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<% if @project.reviews.any? %>
  <h4>Here are the reviews for this project:</h4>

  <ul>
    <% @project.reviews.each do |review| %>
      <li>
        <p>Review: <%= review.content_body %></p>
        <p>Author: <%= review.author %></p>
        <p>Rating: <%= review.rating %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<p><%= link_to "Add a review", new_project_review_path(@project) %></p>

<p><%= link_to "Delete Project", project_path(@project),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to projects", projects_path %></p>

app/views/reviews/new.html.erb
<h1>New review for <%= @product.name %></h1>

<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>